### ISSUE TITLE
Created vs Updated date for timestamp filtering / display

### ISSUE THREAD

**Issue by richardhallett** [datacite/viringo#23]
In the current implementation of OAI-PMH it uses the "updated" date for filtering records on the from/until params and in addition what is displayed as "Datestamp" in the record.

Our own documentation says:
```
from - specifies that records returned must have been
created/update/deleted on or after this date.
until - specifies that records returned must have been
created/update/deleted on or before this date.
```

In the implementation of Viringo so far I've used the created date, this to me makes more sense because if you are attempting to harvest the entire subset of data based upon the updated date the order will change underneath you and this would be bad, whereas the created date is always consistent.

However it is a breaking change, your thoughts @mfenner @kjgarza

**Comment by mfenner** [comment]
I have run into this topic before. Users prefer updated date, as it is otherwise very hard for them to just get the content that has changed. In terms of indexing and deep pagination, the created date is of course preferable.

**Comment by richardhallett** [comment]
Thanks, @kjgarza made similar comments to me, I wasn't considering the use case about wanting updates changes.

I will go ahead and make it match the existing OAI-PMH implementation and our current docs and use updated date.
