### ISSUE TITLE
Restart server after each request in development mode

### ISSUE THREAD

**Issue by mfenner** [datacite/viringo#33]
To enable development in docker environment.

**Comment by mfenner** [comment]
@richardhallett can this be closed? It needs more work, but that may not be needed right now.

**Comment by richardhallett** [comment]
I'm not quite sure where you left it, as I said I don't use docker here, although I did look at the docker config, I think it works sufficiently for anyone who would want to use docker.
Close for now and we can open a new issue for specific issue around automatic reloads if that is required.
