### ISSUE TITLE
Add support for completeListSize and cursor

### ISSUE THREAD

**Issue by mfenner** [datacite/viringo#35]
These are optional elements, but have been supported in the previous OAI-PMH implementation. The `pyoai` library that we are using in `viringo` does not support this functionality.

**Comment by richardhallett** [comment]
I've added support for completeListSize by using a custom XML tree writer (what is used by the pyoai library to output the xml) for overriding.

I've not added in cursor, as I'm not sure it's useful in this context, before it was used to return how many results had been returned so far based upon the paging, however I don't think this number isn't easy to retrieve via the REST API currently, if it's crucial we could investigate returning this number then it is simple to add in.
