### ISSUE TITLE
Incorrect record IDs always throw webserver errors, aren't handled

### ISSUE THREAD

**Issue by axfelix** [datacite/viringo#50]
Currently it looks like inputting an invalid record ID will always throw a 500 error, which prevents us from being compliant with the official OAI spec for deleted records: http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords

**Comment by richardhallett** [comment]
Do you have an example of the 500?

Deleted records, do appear in the DataCite results, so it is compliant to the protocol as far as I can tell.
Any unknown record should return a idDoesNotExist e.g. https://oai.datacite.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=doi:10.1594/ieda/100004ff

**Comment by axfelix** [comment]
Hm, you're right, this appears to be fine upstream whereas I was sure I'd tested it before opening this -- sorry, will double check our own methods.
