### ISSUE TITLE
Error in OAI-PMH

### ISSUE THREAD

**Issue by gjunge** [datacite/viringo#60]
Hello,

Starting from here: https://oai.datacite.org/oai?verb=ListRecords&resumptionToken=metadataPrefix%3Ddatacite%26until%3D2021-07-14T16%253A16%253A31Z%26paging_cursor%3DMTMzNTI0OTg4MzAwMCwxMC4zMjA1L3ptYTAwMDc4OQ%26cursor%3D1

The next continuation token goes into an error page:
https://oai.datacite.org/oai?verb=ListRecords&resumptionToken=metadataPrefix%3Ddatacite%26until%3D2021-07-14T16%253A16%253A31Z%26paging_cursor%3DMTMzNTMxNjA5NjAwMCwxMC4xNTk0L3BhbmdhZWEuNzc4Mzc5%26cursor%3D1

Thanks,
Gidon

**Comment by jrhoads** [comment]
I think this is working now.  @gjunge Give it a try.
I am going to close this for now but can re-open if you are still getting an error.
