### ISSUE TITLE
Draft identifiers appear in OAI-PMH results

### ISSUE THREAD

**Issue by codycooperross** [datacite/viringo#76]
### Describe the bug

Draft identifiers (though not metadata) appear in OAI-PMH results.

#### Expected Behaviour

Draft identifiers should be excluded from OAI-PMH results.

#### Current Behaviour

Draft identifiers appear as deleted with message "This record has been deleted."

#### Steps to Reproduce

Conduct any query in which draft records would appear. 

#### Hypothesis

The API request is authenticated, which returns both draft and registered records. 

https://github.com/datacite/viringo/blob/afc5b7978dfb5aa916f37ac4c2d81fb4ef6a004b/viringo/services/datacite.py#L378

#### Possible Implementation

A query request could be forced to include only registered and findable records.

**Comment by richardhallett** [comment]
Fixed by just requesting findable and registered dois.
Note this may raise some queries as numbers are now different, but realistically this is more correct, drafts should never have appeared.
